---
- hosts: localhost
  become: yes  # Run as root
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    # 1. Enables EPEL repository
    - name: Install epel-release to enable EPEL repository
      package:
        name: epel-release
        state: present

    # 2. Enable Code Ready Builder repository (CRB)
    - name: Enable Code Ready Builder repository (CRB)
      command: yum-config-manager --enable crb
      when: ansible_os_family == "RedHat"  # AlmaLinux is RedHat-based

    # 3. Install development tools for compiling mysqlclient
    - name: Install development tools (GCC and other tools)
      yum:
        name: "@Development tools"
        state: present

    # 4. Install necessary libraries for mysqlclient
    - name: Install MySQL development library
      yum:
        name: mariadb-devel
        state: present

    # 5. Install Apache, MariaDB, PHP, and other required packages
    - name: Install Apache, MariaDB, PHP, and other required packages
      package:
        name:
          - httpd
          - mariadb-server
          - php
          - php-mysqlnd
          - python3
          - openssl-devel
          - wget
          - git
          - unzip
        state: present

    # 6. Install Python development libraries
    - name: Install Python development libraries
      package:
        name: python3-devel
        state: present

    # 7. Install PyMySQL using pip3
    - name: Install PyMySQL using pip3
      ansible.builtin.pip:
        name: PyMySQL
        executable: /usr/bin/pip3

    # 8. Install mysqlclient using pip3
    - name: Install mysqlclient via pip3
      ansible.builtin.pip:
        name: mysqlclient
        executable: /usr/bin/pip3

    # 9. Start and enable Apache (httpd)
    - name: Start and enable Apache (httpd)
      service:
        name: httpd
        state: started
        enabled: yes

    # 10. Start and enable MariaDB
    - name: Start and enable MariaDB (MySQL compatible)
      service:
        name: mariadb
        state: started
        enabled: yes

    # 11. Download WordPress
    - name: Download WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    # 12. Extract WordPress to /var/www/html/
    - name: Extract WordPress to /var/www/html/
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes

    # 13. Set ownership for WordPress files
    - name: Set ownership for WordPress files
      file:
        path: /var/www/html/wordpress
        state: directory
        owner: apache
        group: apache
        mode: '0755'

    # 14. Create MySQL database for WordPress
    - name: Create MySQL database for WordPress
      community.mysql.mysql_db:
        name: wordpress_db
        state: present

    # 15. Create MySQL user for WordPress with all privileges on the database
    - name: Create MySQL user for WordPress
      community.mysql.mysql_user:
        name: wordpress_user
        password: "securepassword"
        priv: 'wordpress_db.*:ALL'
        state: present

    # 16. Copy sample wp-config.php to wp-config.php
    - name: Copy sample wp-config.php to wp-config.php
      copy:
        src: /var/www/html/wordpress/wp-config-sample.php
        dest: /var/www/html/wordpress/wp-config.php

    # 17. Set database name in wp-config.php
    - name: Set database name in wp-config.php
      lineinfile:
        path: /var/www/html/wordpress/wp-config.php
        regexp: 'database_name_here'
        line: "define('DB_NAME', 'wordpress_db');"

    # 18. Set database user in wp-config.php
    - name: Set database user in wp-config.php
      lineinfile:
        path: /var/www/html/wordpress/wp-config.php
        regexp: 'username_here'
        line: "define('DB_USER', 'wordpress_user');"

    # 19. Set database password in wp-config.php
    - name: Set database password in wp-config.php
      lineinfile:
        path: /var/www/html/wordpress/wp-config.php
        regexp: 'password_here'
        line: "define('DB_PASSWORD', 'securepassword');"
